---
openstack:
  ipEndPoint: 192.168.139.136
  username: admin
  password: avi123
  externalNetwork: public
  project:
    name: avicontroller
    description: Avi Control Plane
    domain_id: default
  networks:
    - name: net-avicontroller
      subnet: subnet-avicontroller
      cidr: 192.168.10.0/24
      external: false
      shared: false

  glance:
    - name: Avi-Controller-Qcow2-Image
      fileName: /home/avi/bin/avi/controller-18.1.5-9249.qcow2

  flavor:
    - name: aviFlavor
      ram: 24576
      vcpus: 8
      disk: 100

  key:
    - name: keyPairsAviController
      public_key_file: /home/avi/.ssh/id_rsa.azure.pub

  securityGroups:
    - name: sg-avicontroller
      description: 'security group Avi Control Plane'
      rules:
        - direction: ingress
          protocol: icmp
          port_range_min: -1
          port_range_max: -1
          remote_ip_prefix: 0.0.0.0/0
        - direction: ingress
          protocol: tcp
          port_range_min: 1
          port_range_max: 65535
          remote_ip_prefix: 0.0.0.0/0
        - direction: ingress
          protocol: udp
          port_range_min: 1
          port_range_max: 65535
          remote_ip_prefix: 0.0.0.0/0

  vm:
    key:
      controller: keyPairsAviController
    securitygroup:
      controller: sg-avicontroller
    network:
      controller: net-avicontroller
    image:
      controller: Avi-Controller-Qcow2-Image
    flavor:
      controller: aviFlavor
    controller:
      - name: avicontroller1
        ipAddr: 192.168.10.11
      - name: avicontroller2
        ipAddr: 192.168.10.12
      - name: avicontroller3
        ipAddr: 192.168.10.13
